const DefinitionsActionTypes = {
    OPEN_DEFINITIONS_MODAL: 'OPEN_DEFINITIONS_MODAL',
    CLOSE_DEFINITIONS_MODAL: 'CLOSE_DEFINITIONS_MODAL',
    UPDATE_DEFINITIONS_NUMLINES: 'UPDATE_DEFINITIONS_NUMLINES',
    UPDATE_DEFINITIONS_TEXT: 'UPDATE_DEFINITIONS_TEXT',
    RESET_DEFINITIONS_MODAL: 'RESET_DEFINITIONS_MODAL',
    UPDATE_DEFINITIONS_EXTRASPACE: 'UPDATE_DEFINITIONS_EXTRASPACE',
    ADD_MORE_DEFINITIONS: 'ADD_MORE_DEFINITIONS',
    DELETE_DEFINITION: 'DELETE_DEFINITION',
    UPDATE_DEFINITIONS_ADDHOWTOSOLVE: 'UPDATE_DEFINITIONS_ADDHOWTOSOLVE',
    UPDATE_DEFINITIONS_CHOOSELISTTYPE: 'UPDATE_DEFINITIONS_CHOOSELISTTYPE'
}

export default DefinitionsActionTypes;