const FillGapsActionTypes = {
    OPEN_FILLGAPS_MODAL: 'OPEN_FILLGAPS_MODAL',
    CLOSE_FILLGAPS_MODAL: 'CLOSE_FILLGAPS_MODAL',
    UPDATE_FILLGAPS_TEXT: 'UPDATE_FILLGAPS_TEXT',
    UPDATE_FILLGAPS_ADDHOWTOSOLVE: 'UPDATE_FILLGAPS_ADDHOWTOSOLVE',
    RESET_FILLGAPS: 'RESET_FILLGAPS',
    UPDATE_FILLGAPS_MODE: 'UPDATE_FILLGAPS_MODE',
    UPDATE_FILLGAPS_TEXTSELECTION: 'UPDATE_FILLGAPS_TEXTSELECTION',
    UPDATE_FILLGAPS_ADDSELECTED: 'UPDATE_FILLGAPS_ADDSELECTED',
    UPDATE_FILLGAPS_DELETESELECTED: 'UPDATE_FILLGAPS_DELETESELECTED',
    RESET_FILLGAPS_WORDSSELECTED: 'RESET_FILLGAPS_WORDSSELECTED'
}

export default FillGapsActionTypes;