const TrueFalseActionTypes = {
    OPEN_TRUEFALSE_MODAL: 'OPEN_TRUEFALSE_MODAL',
    UPDATE_TRUEFALSE_TEXT: 'UPDATE_TRUEFALSE_TEXT',
    RESET_TRUEFALSE_MODAL: 'RESET_TRUEFALSE_MODAL',
    CLOSE_TRUEFALSE_MODAL: 'CLOSE_TRUEFALSE_MODAL',
    ADD_MORE_TRUEFALSE: 'ADD_MORE_TRUEFALSE',
    DELETE_TRUEFALSE: 'DELETE_TRUEFALSE',
    UPDATE_TRUEFALSE_ADDHOWTOSOLVE: 'UPDATE_TRUEFALSE_ADDHOWTOSOLVE',
    UPDATE_TRUEFALSE_CHOOSELISTTYPE: 'UPDATE_TRUEFALSE_CHOOSELISTTYPE'
}

export default TrueFalseActionTypes;