const PictogramsActionTypes = {
    SEARCH_PICTOGRAMS: 'SEARCH_PICTOGRAMS',
    ADD_PICTOGRAM: 'ADD_PICTOGRAM',
    FETCH_PICTOGRAMS_SUCCESS: 'FETCH_PICTOGRAMS_SUCCESS',
    OPEN_PICTOGRAMS_MODAL: 'OPEN_PICTOGRAMS_MODAL',
    CLOSE_PICTOGRAMS_MODAL: 'CLOSE_PICTOGRAMS_MODAL',
    INSERT_PICTOGRAM: 'INSERT_PICTOGRAM'
}

export default PictogramsActionTypes;