const DevelopActionTypes = {
    OPEN_DEVELOP_MODAL: 'OPEN_DEVELOP_MODAL',
    UPDATE_DEVELOP_NUMLINES: 'UPDATE_DEVELOP_NUMLINES',
    UPDATE_DEVELOP_TEXT: 'UPDATE_DEVELOP_TEXT',
    RESET_DEVELOP_MODAL: 'RESET_DEVELOP_MODAL',
    CLOSE_DEVELOP_MODAL: 'CLOSE_DEVELOP_MODAL',    
    UPDATE_DEVELOP_EXTRASPACE: 'UPDATE_DEVELOP_EXTRASPACE',
    UPDATE_DEVELOP_ADDHOWTOSOLVE: 'UPDATE_DEVELOP_ADDHOWTOSOLVE'
}

export default DevelopActionTypes;